class UserAlreadyExistsError(Exception): ...


class AuthError(Exception): ...
